// Copy for the single implemented scene. Later steps are navigation only.
export const solutionsHomeCopy = {
  en: {
    eyebrow: 'STEP 1 OF 6',
    title: 'Let’s start',
    titleLead: 'with',
    titleAccent: 'your home',
    intro:
      'Enter your location and electricity use to create the starting point for your solar analysis.',
    region: 'Region',
    chooseRegion: 'Choose your region',
    consumption: 'Electricity use',
    bill: 'Monthly bill',
    usage: 'Monthly kWh',
    amountBill: 'Average monthly bill',
    amountUsage: 'Average monthly usage',
    billHelp: 'You’ll confirm your electricity tariff in the calculator.',
    usageHelp: 'Use the monthly consumption shown on your bill.',
    submit: 'Start my analysis',
    continue: 'Continue',
    full: 'Open full calculator',
    country: 'Armenia',
    location: 'Your location',
    resource: 'Solar resource',
    pending: 'Calculated with PVGIS after you start',
    source: 'Source',
    production: 'Annual production',
    capacity: 'System capacity',
    panels: 'Panels',
    perYear: 'kWh/year',
    lighting: 'Scene lighting preview',
    day: 'Day',
    night: 'Night',
    signature: 'A brighter Armenia together',
    caption: 'SOLAR SOLUTIONS FOR HOMES AND BUSINESSES',
    scroll: 'Scroll to continue',
    progress: 'Your solar journey',
    steps: [
      'Your Home',
      'Roof Details',
      'System Design',
      'Your Savings',
      'Installation',
      'Lifetime Support'
    ],
    trust: [
      ['Accurate solar data', 'Based on PVGIS'],
      ['Official electricity tariffs', 'Armenia registry'],
      ['Transparent calculations', 'Sources and assumptions shown']
    ]
  },
  ru: {
    eyebrow: 'ШАГ 1 ИЗ 6',
    title: 'Начнём',
    titleLead: 'с',
    titleAccent: 'вашего дома',
    intro:
      'Укажите регион и потребление электричества — это отправная точка анализа вашей солнечной системы.',
    region: 'Регион',
    chooseRegion: 'Выберите регион',
    consumption: 'Электроэнергия',
    bill: 'Счёт за месяц',
    usage: 'kWh за месяц',
    amountBill: 'Средний счёт за месяц',
    amountUsage: 'Среднее потребление за месяц',
    billHelp: 'Тариф на электричество вы подтвердите в калькуляторе.',
    usageHelp: 'Укажите месячное потребление из вашего счёта.',
    submit: 'Начать мой анализ',
    continue: 'Продолжить',
    full: 'Открыть полный калькулятор',
    country: 'Армения',
    location: 'Ваш регион',
    resource: 'Солнечный ресурс',
    pending: 'Рассчитаем с PVGIS после начала анализа',
    source: 'Источник',
    production: 'Годовая генерация',
    capacity: 'Мощность системы',
    panels: 'Панели',
    perYear: 'kWh/год',
    lighting: 'Предпросмотр освещения сцены',
    day: 'День',
    night: 'Ночь',
    signature: 'Светлое будущее Армении — вместе',
    caption: 'СОЛНЕЧНЫЕ РЕШЕНИЯ ДЛЯ ДОМА И БИЗНЕСА',
    scroll: 'Листайте дальше',
    progress: 'Путь к вашей солнечной системе',
    steps: ['Ваш дом', 'Детали крыши', 'Проект системы', 'Ваша экономия', 'Установка', 'Поддержка'],
    trust: [
      ['Солнечные данные', 'На основе PVGIS'],
      ['Официальные тарифы', 'Реестр Армении'],
      ['Прозрачный расчёт', 'Источники и допущения']
    ]
  },
  hy: {
    eyebrow: 'ՔԱՅԼ 1 / 6',
    title: 'Սկսենք',
    titleLead: '',
    titleAccent: 'ձեր տնից',
    intro:
      'Նշեք մարզը և էլեկտրաէներգիայի սպառումը՝ ձեր արևային համակարգի վերլուծությունը սկսելու համար։',
    region: 'Մարզ',
    chooseRegion: 'Ընտրեք մարզը',
    consumption: 'Էլեկտրաէներգիա',
    bill: 'Ամսական հաշիվ',
    usage: 'Ամսական kWh',
    amountBill: 'Միջին ամսական հաշիվ',
    amountUsage: 'Միջին ամսական սպառում',
    billHelp: 'Էլեկտրաէներգիայի սակագինը կհաստատեք հաշվիչում։',
    usageHelp: 'Նշեք ձեր հաշվում նշված ամսական սպառումը։',
    submit: 'Սկսել իմ վերլուծությունը',
    continue: 'Շարունակել',
    full: 'Բացել ամբողջական հաշվիչը',
    country: 'Հայաստան',
    location: 'Ձեր մարզը',
    resource: 'Արևային ռեսուրս',
    pending: 'Կհաշվարկվի PVGIS-ով՝ վերլուծությունը սկսելուց հետո',
    source: 'Աղբյուր',
    production: 'Տարեկան արտադրություն',
    capacity: 'Համակարգի հզորություն',
    panels: 'Վահանակներ',
    perYear: 'kWh/տարի',
    lighting: 'Տեսարանի լուսավորության նախադիտում',
    day: 'Ցերեկ',
    night: 'Գիշեր',
    signature: 'Միասին՝ ավելի լուսավոր Հայաստան',
    caption: 'ԱՐԵՎԱՅԻՆ ԼՈՒԾՈՒՄՆԵՐ ՏԱՆ ԵՎ ԲԻԶՆԵՍԻ ՀԱՄԱՐ',
    scroll: 'Ոլորեք՝ շարունակելու համար',
    progress: 'Ձեր արևային համակարգի ուղին',
    steps: [
      'Ձեր տունը',
      'Տանիքի տվյալներ',
      'Համակարգի նախագիծ',
      'Ձեր խնայողությունը',
      'Տեղադրում',
      'Աջակցություն'
    ],
    trust: [
      ['Արևային տվյալներ', 'PVGIS-ի հիման վրա'],
      ['Պաշտոնական սակագներ', 'Հայաստանի ռեեստր'],
      ['Թափանցիկ հաշվարկ', 'Աղբյուրներ և ենթադրություններ']
    ]
  }
};
